name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node18:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        express-version: ['4.18.2', '5.0.0-beta.1']
        fastify-version: ['4.25.2', '5.7.2']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: |
          npm ci
          npm install express@${{ matrix.express-version }} fastify@${{ matrix.fastify-version }}
        working-directory: ./apipackge
      - name: Build
        run: npm run build
        working-directory: ./apipackge
      - name: Run tests
        run: npm test
        working-directory: ./apipackge

  node20:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        express-version: ['4.18.2', '5.0.0-beta.1']
        fastify-version: ['4.25.2', '5.7.2']
        koa-version: ['2.14.2']
        hono-version: ['3.11.7', '4.11.7']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          npm ci
          npm install express@${{ matrix.express-version }} fastify@${{ matrix.fastify-version }} koa@${{ matrix.koa-version }} hono@${{ matrix.hono-version }}
        working-directory: ./apipackge
      - name: Build
        run: npm run build
        working-directory: ./apipackge
      - name: Run tests
        run: npm test
        working-directory: ./apipackge
